name: Executar Testes

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar Repositório
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar Dependências
        run: dotnet restore ScreenSound.sln
        working-directory: ScreenSound

      - name: Executar Testes
        run: dotnet test ScreenSound.sln --logger "trx;LogFileName=resultado_teste.trx" --filter Categoria=Integração
        working-directory: ScreenSound

      - name: Salvar Relatório Testes
        uses: actions/upload-artifact@v4
        with:
          name: resultado-Testes
          path: resultado_teste.trx